# -*- coding: utf-8 -*-
"""2. 영업시간,배달여부.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vr8X2rWXghh5ksS8eg0HZ5qtqUYBkZSg
"""

# 폰트 설치 
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

from google.colab import drive
drive.mount('/content/gdrive')
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import itertools
from itertools import chain, repeat

df = pd.read_csv('/content/gdrive/MyDrive/파데분플젝/5가지 정보제공메뉴/배달_영업시간.csv')

while True:
    mode = int(input('모드를 골라주세요: 1 - 검색 모드: , 2 - 프로그램 종료: '))


    if mode == 1:
        print()
        store=input("영업시간과 배달 가능 여부를 알고 싶은 가게 이름을 입력하세요: ")
        ii=df.index[df['상호명'].str.contains(store)].tolist() 
        i=ii[0]
        if df['office_hour_end'][i]=='n':
            print()
            print('❗'+'<'+df['상호명'][i]+">은 영업시간이 표시되어 있지 않은 가게입니다"+'❗')
        else:
            start=int(df['office_hour_start'][i][:2])
            end=int(df['office_hour_end'][i][:2])
            x=np.arange(start,end+1)
            y=list(repeat(1,len(x)))
            df_=pd.DataFrame(y,x,columns=['영업 중'])
            df_.index = df_.index.map(int)
            plt.style.use('ggplot')
            plt.rc('font', family='NanumBarunGothic')
            df_.plot(kind='area',stacked=False,alpha=0.2,figsize=(14,0.7),xticks=np.arange(0,25),yticks=np.arange(2,3))
            plt.title('<'+df['상호명'][i]+'>'+"의 영업시간: "+df['office_hour_start'][i]+'~'+df['office_hour_end'][i]) 
            plt.xlabel('00:00a.m.~24:00p.m.',size=10)
            plt.ylabel('영업',size=10)
            plt.show()
        print()
        print('   배달 가능 여부')
        if df['delivery_bool'][i]=='Yes':
            print('🛵'+'<'+df['상호명'][i]+">은 배달 가능한 가게입니다")
            print('------------------------------------------------------------------------------------------------------')
        else:
            print('❗'+'<'+df['상호명'][i]+">은 배달이 불가능하거나 배달 여부가 표시되어 있지 않은 가게입니다"+'❗')
            print('------------------------------------------------------------------------------------------------------')
        
    elif mode == 2:
        print()
        print('이용해 주셔서 감사합니다')
        break    
    
    else:
        print('잘못된 숫자를 입력하셨습니다. 다시 입력해주세요 ')
