# -*- coding: utf-8 -*-
"""1. 위치 시각화, 주소 및 거리.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kOnE5jDtJlnqcMIRtEZd2pobFbsC3ZT5
"""

import pandas as pd
from geopy.distance import geodesic
import folium
from folium.plugins import MarkerCluster

from google.colab import drive
drive.mount('/content/gdrive')

dfm= pd.read_csv('/content/gdrive/MyDrive/파데분플젝/5가지 정보제공메뉴/folium위치시각화/남가좌1동.csv')
df=pd.DataFrame(dfm.loc[:,'경도':'위도'],columns=['경도','위도'])

while True:
    mode = int(input('모드를 골라주세요: 1 - 해당 동 뷰 모드, 2 - 검색 모드: , 3 - 프로그램 종료: '))

    if mode == 1:
        lat=df['위도'].mean()
        long=df['경도'].mean()
        m1=folium.Map(location = [lat, long], zoom_start=13)
        marker_cluster=MarkerCluster().add_to(m1)
        for i in dfm.index:
            sub_lat=df.loc[i,'위도']
            sub_long=df.loc[i,'경도']

            folium.Marker([sub_lat, sub_long],
                          icon=folium.Icon(color='orange', icon = 'glyphicon-cutlery'),
                          tooltip='<b>' + str(dfm.loc[i,'상호명']) + '</b>').add_to(marker_cluster)
        print()
        print('<남가좌 1동>의 음식점 위치에 대한 정보입니다.')
        display(m1)
        print('------------------------------------------------------------------------------------------------------')

        
    elif mode == 2:
        print()
        print('나의 위치를 입력해주세요: ')
        my_lat = float(input('위도를 입력해주세요(-90~90): ')) 
        my_long = float(input('경도를 입력해주세요(-180~180): ')) 
        print()
        store=input("주소와 나와의 거리를 알고 싶은 가게 이름을 입력하세요: ")
        ii=dfm.index[dfm['상호명'].str.contains(store)].tolist() 
        
        i=ii[0]
        store_location = (df['위도'][i],df['경도'][1])
        my_location = (my_lat, my_long)

        df['distance']=df.apply(lambda x:geodesic((x['위도'],x['경도']),my_location),axis=1)
        
        m2=folium.Map(location = [(store_location[0] + my_location[0]) / 2, (store_location[1] + my_location[1]) / 2], zoom_start=12)

        folium.Marker(store_location, tooltip= '<b><i>'+str(dfm['상호명'][i])+'</b></i>',
                      icon=folium.Icon(color='blue', icon='search'),
                      popup='<i>도로명주소:</i>' + '<br/>' + dfm['도로명주소'][i] 
                      + '<br/>'* 2  + '<i>나와의 거리:</i>' + '<br/>' + str(df['distance'][i])).add_to(m2)

        folium.Marker(my_location, tooltip = '<i><b>나의 위치</b></i>', icon = folium.Icon(color = 'red', icon = 'user')).add_to(m2)
        print()
        print('<'+dfm['상호명'][i],'>의 주소, 거리에 대한 정보입니다.')
        display(m2)
        print('------------------------------------------------------------------------------------------------------')
        
        
    elif mode == 3:
        print()
        print('이용해 주셔서 감사합니다')
        break
        
    else:
        print('잘못된 숫자를 입력하셨습니다. 다시 입력해주세요 ')